CREATE TABLE IF NOT EXISTS CLIENTE (
	ID INTEGER GENERATED ALWAYS AS IDENTITY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDOS VARCHAR(50) NOT NULL,
	FECHA_NAC DATE NOT NULL,
	DNI VARCHAR(9) UNIQUE NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	NACIONALIDAD VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	ACTIVO BOOLEAN DEFAULT TRUE,
	CONSTRAINT CLIENTE_PK PRIMARY KEY (ID)
);
	
CREATE TABLE IF NOT EXISTS VENTA_ORO(
	ID INTEGER GENERATED ALWAYS AS IDENTITY,
	FECHA DATE UNIQUE NOT NULL,
	PRECIO_KG NUMERIC(12,2) NOT NULL,
	CONSTRAINT VENTA_ORO_PK PRIMARY KEY (ID)
	
);

CREATE TABLE IF NOT EXISTS TASACION(
	ID INTEGER GENERATED ALWAYS AS IDENTITY,
	CLIENTE_ID INTEGER NOT NULL,
	FECHA_TASACION DATE NOT NULL,
	PESO_GRAMOS NUMERIC(10,2) NOT NULL,
	PRECIO_ORO_KG_EN_FECHA NUMERIC (12,2) NOT NULL,
	IMPORTE NUMERIC(12,2) DEFAULT 0,
	ESTADO VARCHAR(10) NOT NULL,
	CONSTRAINT TASACION_PK PRIMARY KEY (ID),
	CONSTRAINT TASACION_FK FOREIGN KEY (CLIENTE_ID)
	   REFERENCES CLIENTE(ID)
);